#ifndef __HID_CMD_TABLE
#define __HID_CMD_TABLE

#define APP_EVENT_COUNT										12

typedef enum {
	HID_CMD_EVENT_REQUEST = 0xF1,
	HID_CMD_EVENT_RESPONSE
} GW_HID_EVENT_E;

typedef enum {
	GW_HID_CMD_TEST_BASE = 0x00,
	GW_HID_CMD_TEST,
	GW_HID_CMD_ECHO,
	GW_HID_CMD_AW5808_UPGRADE = 0x10,
	GW_HID_CMD_VERSION_GET,
	GW_HID_CMD_CONFIGURATION_SET,
	GW_HID_CMD_DEVICE_INFO_GET,
	GW_HID_CMD_3607D_UPGRADE,
	GW_HID_CMD_RUN_MODE_BASE = 0x70,
	GW_HID_CMD_ROM_REBOOT,
	GW_HID_CMD_ROM_MODE,
	GW_HID_CMD_WILDCARD = 0xFF
} GW_HID_CMD_TABLE_E;

#endif