#pragma once

typedef enum {
    USB_STATE_SUCCESS = 0,
    USB_STATE_CONNECTION_FAILED = 1
} USB_STATE_E;

typedef enum {
    ISP_STATE_SUCCESS = 0,
    ISP_STATE_HID_CONNECTION_FAILED,
    ISP_STATE_ISP_PROCESS_FAILED,
    ISP_STATE_ISP_CONNECTION_FAILED,
    ISP_STATE_UPGRADE_FAILED,
} ISP_STATE_E;
